// app/src/views/Login.tsx
import { useMutation } from "@apollo/client";
import { FC, SyntheticEvent } from "react";
import { Link, useHistory } from "react-router-dom";
import img from "../assets/digital-landscape.jpg";
import { Error } from "../components/Error";
import { Loading } from "../components/Loading";
import { useUpdateAccessToken } from "../contexts/AccessTokenContext";
import { ILogin } from "../types";
import { LOGIN } from "../graphql/mutation/LOGIN";
import { useUpdateMessage } from "../contexts/MessageContext";
import { useUpdateSuccess } from "../contexts/SuccessContext";
import { useUpdateUser } from "../contexts/UserContext";

export const Login: FC = () => {
	const history = useHistory();

	const updateAccessToken: Function = useUpdateAccessToken();
	const updateMessage: Function = useUpdateMessage();
	const updateSuccess: Function = useUpdateSuccess();
	const updateUser: Function = useUpdateUser();

	const [loginFunc, { 
		loading: loginLoading, 
		error: loginError, 
	}] = useMutation<ILogin>(LOGIN, {
		onCompleted: ({ login }) => {
			updateMessage(login.message);
			updateSuccess(login.success);
			
			if (login.success && login.accessToken && login.username) {
				localStorage.setItem("access_token", login.accessToken);
				updateAccessToken(login.accessToken);
				updateUser(login.username);
				
				return history.replace("/");
			}
		}
	});

	if (loginLoading) return <Loading />;
	if (loginError) return <Error />;

	const handlers = {
		submit: async (e: SyntheticEvent<HTMLFormElement>) => {
			e.preventDefault();
			
			const { username, password }: any = Object.fromEntries(new FormData(e.currentTarget));

			try {
				await loginFunc({
					variables: {
						input: {
							username,
							password
						}
					}
				});				
			} catch (err) {
				console.error(err);
			}
		}
	}

	return (
		<div>
			<div className="login-img-wrapper">
				<img src={img} alt="Digital Landscape" className="w-full h-full object-fill" />
			</div>
			<form onSubmit={handlers.submit} className="absolute transform top-1/2 left-1/2 -translate-y-1/2 -translate-x-1/2 p-5 bg-white-background w-1/4">
				<input required type="text" placeholder="Username" name="username" className="w-full mb-2.5 border border-solid border-default-border-color px-2.5 py-1.5 focus:border-primary outline-none" /><br />
				<input required type="text" placeholder="Password" name="password" className="w-full mb-2.5 border border-solid border-default-border-color px-2.5 py-1.5 focus:border-primary outline-none" /><br />
				<button type="submit" className="bg-primary text-white-text font-bold w-full p-1.5">Log In</button>
				<p className="text-center mt-2.5 underline text-blue-600"><Link to="/register">Don't have an account yet?</Link></p>
			</form>
		</div>
	);
}

// client/src/views/Login.vue
<template>
	<ApolloMutation
		:mutation="gql => gql`
			mutation($input: UserInput!) {
				login(input: $input) {
					message
					access_token
					wrongCredentials
					refresh_token
				}
			}
		`"
		:variables="{ 
			input: {
				username,
				password
			}
		}"
		@done="onDone"
	>
		<template v-slot="{ mutate, loading, error }">
			<Loading v-if="loading" />
			<p v-if="error">An Error Occured.</p>
			<div class="login" v-else>
				<div>
					<img src="@/assets/login-image.jpeg" />
				</div>
				<form @submit.prevent="mutate()">
					<input type="text" placeholder="Username" name="username" v-model="username" /><br>
					<input type="text" placeholder="Password" name="password" v-model="password" /><br>
					<button type="submit">Log In</button>
					<p class="register-link"><router-link to="/register">Don't have an account yet?</router-link></p>
					<Message v-if="message" :message="message" :error="wrongCredentials" />
				</form>
			</div>
		</template>
	</ApolloMutation>
</template>

<script>
import Loading from '../components/Loading.vue';
import Message from '../components/Message.vue';

export default {
  components: { 
		Loading,
		Message
	},
	data: () => ({
		username: "",
		password: "",
		message: "",
		wrongCredentials: false
	}),
	methods: {
		onDone({ data }) {
			this.message = data.login.message;
			this.wrongCredentials = data.login.wrongCredentials;
			
		}
	}
}
</script>

<style lang="scss">
@import "@/scss/variables.scss";

.login {
	display: flex;
	align-items: center;

	div:first-child {
		width: 75%;
	}

	img {
		width: 100%;
		height: calc(100vh - 66px);
	}

	form {
		background-color: white;
		height: calc(100vh - 66px);
		width: 25%;
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		padding: 1.5rem;

		input {
			// margin-bottom: 1rem;
			width: 100%;
			font-size: 1.5rem;
			padding: 1rem 1rem;
		}

		button {
			width: 100%;
			
		}
	}
}
.register-link {
	margin-top: 1rem;
	text-align: center;
	font-size: 1.2rem;
}
</style>
